import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "@krrli/cm-designsystem/dist/cm-designsystem.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div style={{ paddingTop: "80px" }}>{children}</div>
      </body>
    </html>
  );
}
